services:
  spacerework:
    env_file: ../../.env
    platform: linux/amd64
    image: ${APP_NAME}-app-image
    container_name: ${APP_NAME}-app-container
    hostname: ${APP_NAME}-app-container
    build:
      context: ../../
      dockerfile: ./docker/app/Dockerfile
      args:
        RUST_VERSION: 1.83
        BASE_OS: bookworm # Using Debian-bookworm instead of Alpine because V8 compilation fails due to a tricky bug: https://github.com/denoland/rusty_v8/issues/49
        NODE_VERSION: 22.10.0
        TUONO_VERSION: 0.17.6
    ports:
      - '3000:3000'
    volumes: # mount the project into a volume but node_modules, target and .tuono directories will be empty in host-side
      - ../..:/app
    tty: true
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME}-docker-network