//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::lesson::Entity as Lesson;
pub use super::path_segment::Entity as PathSegment;
pub use super::path_segment_type::Entity as PathSegmentType;
pub use super::user::Entity as User;
