//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "segment_type_name")]
pub enum SegmentTypeName {
    #[sea_orm(string_value = "directory")]
    Directory,
    #[sea_orm(string_value = "lesson")]
    Lesson,
}
