//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "segment_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::path_segment::Entity")]
    PathSegment,
}

impl Related<super::path_segment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PathSegment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
