services:
  front:
    container_name: spacerework-container
    build:
      context: . # Path to the directory where the Dockerfile is located
      dockerfile: Dockerfile
    image: spacerework-image
    ports:
      - "3000:3000"
    volumes:
      # Volumes are mounted when the container starts
      # but before the CMD / ENTRYPOINT commands
      - ./src:/app/src
      # - ./tests:/app/tests
    tty: true
