services:
  front:
    container_name: spacerework-container
    build:
      context: . # Chemin du répertoire où se trouve le Dockerfile
      dockerfile: Dockerfile
    image: spacerework-image
    ports:
      - "3000:3000"
    volumes:
      # Les volumes sont montés lors du démarrage du conteneur
      # mais avant les commandes CMD / ENTRYPOINT
      - ./src:/app/src
      # - ./tests:/app/tests
    tty: true