services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_CONFIG_SERVER_MODE=False # disables the pgadmin4 login screen
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False # removes the need to enter the master password when the login screen is disabled
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      # - ./.pgpass:/tmp/.pgpass
    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME}-docker-network
